-- 코드를 입력하세요
SELECT 
BOOK_ID,
TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD')as PUBLISHED_DATE
FROM BOOK
where PUBLISHED_DATE >= DATE '2021-01-01'
and PUBLISHED_DATE <= DATE '2021-12-31'
and CATEGORY like '%인문%'
order by PUBLISHED_DATE ASC;