-- 코드를 입력하세요
SELECT
BOARD_ID,
WRITER_ID,
TITLE,
PRICE,
CASE
    when STATUS = 'SALE' THEN '판매중'
    when STATUS = 'RESERVED' THEN '예약중'
    ELSE '거래완료'
end as STATUS
from USED_GOODS_BOARD
where TO_CHAR(CREATED_DATE,'YYYY-MM-DD') ='2022-10-05'
order by BOARD_ID DESC